config/routes.rb
Myfinance::Application.routes.draw do
  resources :users do
    member do
      get 'settings'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :stock_watchlists

  root :to => 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/stock_watchlists/filter', to: 'stock_watchlists#filter'

  get "static_page_controller/home" 
  get "static_page_controller/help"
  get "static_page_controller/about"
  get "static_page_controller/contact"

end

app/models/stock_watchlist.rb
class StockWatchlist < ActiveRecord::Base
  attr_accessible :classification, :notes, :exchange, :symbol, :watch_parameter_attributes, 
    :tags_attributes

  validates :symbol, presence: true, length: {maximum: 15}, uniqueness: true
  validates :exchange, presence: true
  validates :classification, presence: true
  validates :notes, length: {maximum: 128}

  has_one :watch_parameter, dependent: :destroy, primary_key: "symbol", foreign_key: "symbol"
  accepts_nested_attributes_for :watch_parameter, allow_destroy:true

  has_one :stock_data, dependent: :destroy, primary_key: "symbol", foreign_key: "symbol"

  has_many :tags, as: :taggable, dependent: :destroy
  accepts_nested_attributes_for :tags, reject_if: lambda {|a| a[:name].blank?}, allow_destroy:true

  VALID_EXCHANGE_REGEX = /NSE|BSE/
  validates :exchange, presence: true, format: {with: VALID_EXCHANGE_REGEX}

  CLASSIFICATION_INVESTMENT = "INVESTMENT"
  CLASSIFICATION_TRADING = "TRADING"

  VALID_CLASSIFICATION_REGEX = /INVESTMENT|TRADING/
  validates :classification, presence: true, format: {with: VALID_CLASSIFICATION_REGEX}
  
  before_create :build_default_watch_parameter, :build_default_stock_data
  before_save {|stock_watchlist| stock_watchlist.symbol = stock_watchlist.symbol.upcase}

  # class level methods
  def self.search(classifications, watch_parameters, tag_names)
    stocks = scoped

    stocks = stocks.where("classification in (?)", classifications) unless classifications.to_a.empty? 
    stocks = stocks.joins(:tags).where("name in (?)",tag_names ).
      group("'stock_watchlists'.id") unless tag_names.to_a.empty?

    return stocks
  end

  def self.update_price(symbols = nil)
    puts "updating stock price"
    stock_watchlist_objects = scoped
    stock_watchlist_objects = where('symbol in (?)', symbols) if symbols

    stock_symbols = stock_watchlist_objects.collect { |obj| [obj.symbol, obj.exchange]}
    
    stock_prices = StockQuoteHelper::get_price(stock_symbols)
    stock_prices.each { |key_symbol, price_object| 
      stock_watchlist_objects.find_by_symbol(StockQuoteHelper::normalize_symbol(key_symbol)).
        stock_data.update_attributes(price: price_object.lastTrade) }
  end

  private
    def build_default_stock_data
      build_stock_data
      true
    end

    def build_default_watch_parameter
      build_watch_parameter
      true
    end
end

app/controllers/stock_watchlists_controller.rb
class StockWatchlistsController < ApplicationController
  before_filter :signed_in_user

  def new
    @stock_watchlist = StockWatchlist.new
    @stock_watchlist.build_watch_parameter
    3.times {@stock_watchlist.tags.build}
  end

  def create 
    @stock_watchlist = StockWatchlist.new(params[:stock_watchlist])
    if @stock_watchlist.save 
      flash[:success] = "Stock #{@stock_watchlist.symbol} added successfully"
      redirect_to stock_watchlists_path
    else
      render 'new'
    end
  end

  def edit
    @stock_watchlist = StockWatchlist.find_by_symbol(params[:id])
  end

  def update 
    @stock_watchlist = StockWatchlist.find(params[:id])
    if @stock_watchlist.update_attributes(params[:stock_watchlist])
      flash[:success] = "Stock #{@stock_watchlist.symbol} updated successfully"
      redirect_to stock_watchlists_path
    else
      render 'edit'
    end
  end
  
  def show
    @stock_watchlist = StockWatchlist.find_by_symbol(params[:id])
  end

  def destroy
    StockWatchlist.find(params[:id]).destroy
    flash[:success] = "Stock removed successfully"


    respond_to do |format|
      format.html {redirect_to stock_watchlists_path}
      format.js {@stock_watchlists = search_stocks}
    end
  end

  def index
    @stock_tags ||= Tag.unique_stock_tags
    @stock_watchlists = search_stocks

    respond_to do |format|
      format.html       
      format.js
    end
  end

  private
    def search_stocks
      @filter_investment = params[:filter_investment]
      @filter_trading = params[:filter_trading]
      @filter_tags = params[:filter_tags]


      filter_classification = [@filter_investment, @filter_trading]
      StockWatchlist.search(filter_classification.delete_if{|x| x == nil},
                                      nil,@filter_tags).paginate(page: params[:page], per_page: 25)
    end
end

app/helpers/stock_watchlist_helper.rb
module StockWatchlistHelper
end

app/views/stock_watchlists/_fields.html.erb
<legend>Basic Stock Details</legend>    
<div class="control-group">
  <!-- Text input-->
  <%= f.label :symbol, class: "control-label"%>
  <div class="controls">
    <% disable = true unless f.object.new_record? %>
    <%= f.text_field :symbol, disabled: disable%>
    <p class="help-block">Enter Stock Symbol</p>
  </div>
</div>

<div class="control-group">
  <!-- Select Exchange -->
  <%= f.label :exchange, class: "control-label"%>
  <div class="controls">
    <%= f.select :exchange, ["NSE","BSE"]%>
  </div>
</div>
    

<div class="control-group">
<!-- Select Classification -->
  <%= f.label :classification, class: "control-label"%>
  <div class="controls">
      <%= f.select :classification, ["INVESTMENT","TRADING"]%>
  </div>
</div>

<div class="control-group">
<!-- Textarea -->
  <%= f.label :notes, class: "control-label"%>
  <div class="controls">
  <div class="textarea">
    <%= f.text_area :notes, rows:5%>
  </div>
  </div>
</div>

app/views/stock_watchlists/_filter_criteria.html.erb
<div class="control-group">
  <label class="control-label">Classification</label>
  <!-- Multiple Checkboxes -->
  <div class="controls">
    <!-- Inline Checkboxes -->
    <%= label_tag(:filter_investment, "Investments", class: "checkbox inline") %>
    <%= check_box_tag(:filter_investment,"INVESTMENT",@filter_investment == 'INVESTMENT',:onchange => "$(this).submit()" ) %>  
    <%= label_tag(:filter_trading, "Trading", class: "checkbox inline") %>
    <%= check_box_tag(:filter_trading,"TRADING",@filter_trading == 'TRADING',:onchange => "$(this).submit()") %>  
  </div>
</div>

<div class="control-group">
  <label class="control-label">Watch Parameters</label>
  <!-- Multiple Checkboxes -->
  <div class="controls">
    <!-- Inline Checkboxes -->
    <%= label_tag(:filter_50_ema, "50 EMA", class: "checkbox inline") %>
    <%= check_box_tag(:filter_50_ema, :onclick => "$(this).submit()") %>  
    <%= label_tag(:filter_100_ema, "100 EMA", class: "checkbox inline") %>
    <%= check_box_tag(:filter_100_ema, :onclick => "$(this).submit()") %>  
    <%= label_tag(:filter_200_ema, "200 EMA", class: "checkbox inline") %>
    <%= check_box_tag(:filter_200_ema, :onclick => "$(this).submit()") %>  
    <%= label_tag(:filter_resistance, "Resistance", class: "checkbox inline") %>
    <%= check_box_tag(:filter_resistance, :onclick => "$(this).submit()") %>  
    <%= label_tag(:filter_breakout, "Breakout", class: "checkbox inline") %>
    <%= check_box_tag(:filter_breakout, :onclick => "$(this).submit()") %>  
    <%= label_tag(:filter_price, "Price", class: "checkbox inline") %>
    <%= check_box_tag(:filter_price, :onclick => "$(this).submit()") %>  
  </div>
</div>

<div class="control-group">
  <label class="control-label">Tags</label>
  <!-- Multiple Checkboxes -->
  <div class="controls">
    <!-- Inline Checkboxes -->
    <%= select_tag(:filter_tags, options_from_collection_for_select(@stock_tags, :name, :name, @filter_tags), multiple: true, onchange: "$(this).submit()") %>
  </div>
</div>

app/views/stock_watchlists/_stock_watchlist.html.erb
<tr>
  <td>
  <%= link_to stock_watchlist.symbol, edit_stock_watchlist_path(stock_watchlist.symbol) %>
  </td>
  <td>
  <%= number_with_precision(stock_watchlist.stock_data.price, precision:2)%>
  </td>
  <td>
  <%= stock_watchlist.classification %>
  </td>
  <td>
  <%= stock_watchlist.notes%>
  </td>
  <td>
  <!--
  <%= link_to "Delete", stock_watchlist, method: :delete, data: { confirm: "You sure?" }, id: "delete_stock_watchlist"%>
  -->
  <%= form_for(stock_watchlist, html: { method: :delete },  remote: true) do |f| %>
    <% if @filter_investment && !@filter_investment.empty? %>
      <%= hidden_field_tag :filter_investment, @filter_investment %>
    <% end %>
    <% if @filter_trading && !@filter_trading.empty? %>
      <%= hidden_field_tag :filter_trading, @filter_trading%>
    <% end %>
    <% if @filter_tags && !@filter_tags.empty? %>
      <%= hidden_field_tag :filter_tags, @filter_tags%>
    <% end %>
    <%= f.submit "Delete", data: { confirm: "You sure?" },class: "btn btn-primary btn-small", id: "delete_stock_watchlist"%>
  <% end %>  
  </td>
</tr>

app/views/stock_watchlists/_stock_watchlist_table.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Price</th>
      <th>Classification</th>
      <th>Notes</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  <%= render @stock_watchlists%>
  </tbody>
</table>

app/views/stock_watchlists/_tags.html.erb
<div class="control-group">
  <!-- Text input-->
  <%= f.label :name, "Tag", class: "control-label"%>
  <div class="controls">
    <%= f.text_field :name%>
    <%= f.label :_destroy, "Remove Tag", class: "checkbox inline"%>
    <%= f.check_box :_destroy %>
  </div>
</div>

app/views/stock_watchlists/_tags_section.html.erb
<legend>Stock Tags</legend>    
<%= f.fields_for :tags do |ff| %>
  <%= render 'tags', f:ff %>
<% end %>

app/views/stock_watchlists/_watch_parameters.html.erb
<legend>Watch Parameters</legend>    
<div class="control-group">
  <label class="control-label">Moving Averages</label>

  <!-- Multiple Checkboxes -->
  <div class="controls">
  <!-- Inline Checkboxes -->
  <%= f.label :ma_50, "50 day", class: "checkbox inline"%>
  <%= f.check_box :ma_50%>
  <%= f.label :ma_100, "100 day", class: "checkbox inline"%>
  <%= f.check_box :ma_100%>
  <%= f.label :ma_200, "200 day", class: "checkbox inline"%>
  <%= f.check_box :ma_200%>
  </div>
</div>


<div class="control-group">
  <!-- Text input-->
  <%= f.label :resistance, class: "control-label"%>
  <div class="controls">
    <%= f.text_field :resistance%>
    <p class="help-block">Enter the resistance level of the stock</p>
  </div>
</div>

<div class="control-group">
  <!-- Text input-->
  <%= f.label :breakout, class: "control-label"%>
  <div class="controls">
    <%= f.text_field :breakout%>
  <p class="help-block">Enter the breakout level of the stock</p>
  </div>
</div>


<div class="control-group">
  <!-- Text input-->
  <%= f.label :price, class: "control-label"%>
  <div class="controls">
    <%= f.text_field :price%>
  <p class="help-block">Enter the watch price level of the stock</p>
  </div>
</div>

app/views/stock_watchlists/destroy.js.erb
$("#flash_notice").html("<%= escape_javascript(render('layouts/flash_notice')) %>")
$("#stock_watchlist_table").html("<%= escape_javascript(render('stock_watchlist_table')) %>")

app/views/stock_watchlists/edit.html.erb
<% provide(:title, 'Edit Stock from Watchlist') %>
<section id="forms">
  <div class="page-header">
    <h1>Edit Stock - <%= @stock_watchlist.symbol %></h1>
  </div>

  <div class="row">
    <div class="span10 offset1">
      <div class="form-horizontal well">      
        <%= form_for(@stock_watchlist) do |f| %>
        <fieldset>
          <%= render 'shared/error_messages', object: f.object %>
          <%= render 'fields', f:f %>
          <%= f.fields_for :watch_parameter do |ff| %>
            <%= render 'watch_parameters', f:ff %>
          <% end %>
          <%= render 'tags_section', f:f %>
          <div class="form-actions">
            <%= f.submit "Save Changes" , class: "btn btn btn-primary" %>
            <%= f.submit "Cancel" , class: "btn" %>
          </div>
        </fieldset>
      <% end %>
      </div>
    </div>
  </div>
</section>

app/views/stock_watchlists/index.html.erb
<% provide(:title, 'Stocks in Watchlist') %>
<div class="page-header">
  <h1>Stocks in Watchlist</h1>
</div>

<section id="forms">
  <div class="row">
    <div class="span12">
      <div class="form-horizontal well">      
      <legend>Choose Filter Criteria</legend>
      <%= form_tag("/stock_watchlists", :method => "get", remote: true) do %>
        <fieldset>
          <%= render "filter_criteria" %>
          <!--
          <div class="form-actions">
            <%= submit_tag("Filter", class: "btn btn-smally") %>
            <%= submit_tag("Reset", class: "btn btn-small") %>
          </div>
          -->
        </fieldset>
      <% end %>

      <section id="tables">
        <legend>List of Stocks</legend>
        <div id="stock_watchlist_table">
          <%= render "stock_watchlist_table"%>
        </div>
        <%= will_paginate @stock_watchlists%>
      </section>
      </div>
    </div>
  </div>
</section>

app/views/stock_watchlists/index.js.erb
$("#stock_watchlist_table").html("<%= escape_javascript(render('stock_watchlist_table')) %>")

app/views/stock_watchlists/new.html.erb
<% provide(:title, 'Add Stock to Watchlist') %>
<section id="forms">
  <div class="page-header">
    <h1>Add Stock to Watchlist</h1>
  </div>

  <div class="row">
    <div class="span10 offset1">
      <div class="form-horizontal well">      
      <%= form_for(@stock_watchlist) do |f| %>
        <fieldset>
          <%= render 'shared/error_messages', object: f.object %>
          <%= render 'fields', f:f %>
          <%= f.fields_for :watch_parameter do |ff| %>
            <%= render 'watch_parameters', f:ff %>
          <% end %>
          <%= render 'tags_section', f:f %>
          <div class="form-actions">
            <%= f.submit "Add Stock" , class: "btn btn btn-primary" %>
            <%= f.submit "Cancel" , class: "btn" %>
          </div>
        </fieldset>
      <% end %>
    </div>
    </div>
  </div>
</section>