config/routes.rb
Myfinance::Application.routes.draw do
  resources :users do
    member do
      get 'settings'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :stock_watchlists

  root :to => 'static_pages#home'
  match '/home', to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/about', to: 'static_pages#about'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/stock_watchlists/filter', to: 'stock_watchlists#filter'

  get "static_page_controller/home" 
  get "static_page_controller/help"
  get "static_page_controller/about"
  get "static_page_controller/contact"

end

app/views/layouts/_flash_notice.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>      

app/views/layouts/_footer.html.erb
<br><br><br><br>

<!-- Footer
================================================== -->
<hr>
<footer id="footer">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <div class="links">
          <%= link_to "Help", help_path%>
          <%= link_to "About", about_path%>
          <%= link_to "Contact", contact_path%>
        </div>
</footer>

app/views/layouts/_header.html.erb
 <!-- Navbar
    ================================================== -->
 <div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">MyFinance</a>
       <div class="nav-collapse" id="main-menu">
         <ul class="nav" id="main-menu-left">
           <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Stock Watchlist<b class="caret"></b></a>
            <ul class="dropdown-menu" id="swatch-menu">
              <li><%= link_to "Add Stock", new_stock_watchlist_path() %></li>
              <li><%= link_to "List of Stocks", stock_watchlists_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Stock Action3", "#" %></li>
            </ul>
            </li>

           <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Utility Bills<b class="caret"></b></a>
            <ul class="dropdown-menu" id="swatch-menu">
              <li><%= link_to "Utility Bill Action1", "#" %></li>
              <li><%= link_to "Utility Bill Action2", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Utility Bill Action3", "#" %></li>
            </ul>
            </li>

           <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Epic Xs<b class="caret"></b></a>
            <ul class="dropdown-menu" id="swatch-menu">
              <li><%= link_to "Epic X Action1", "#" %></li>
              <li><%= link_to "Epic X Action2", "#" %></li>
              <li class="divider"></li>
              <li><%= link_to "Epic X Action3", "#" %></li>
            </ul>
           </li>
        </ul>
        <ul class="nav pull-right" id="main-menu-right">
          <li><%= link_to "Home", root_path%></li>
          <% if signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user%></li>
              <li><%= link_to "Settings", settings_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Sign out", signout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
       </div>
     </div>
   </div>
 </div> 

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div id="flash_notice">
        <%= render "layouts/flash_notice" %>
      </div>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/temp.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>

  <!-- Navbar
      ================================================== -->
   <div class="navbar navbar-fixed-top">
     <div class="navbar-inner">
       <div class="container">
         <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </a>
         <a class="brand" href="../">MyFinance</a>
         <div class="nav-collapse" id="main-menu">
           <ul class="nav" id="main-menu-left">
            <li><%= link_to "News", "#", id: "swatch-link"%></li>             
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Stocks<b class="caret"></b></a>
              <ul class="dropdown-menu" id="swatch-menu">
                <li><%= link_to "Action1", "#" %></li>
                <li><%= link_to "Action2", "#" %></li>
                <li><%= link_to "Action3", "#" %></li>
                <li><%= link_to "Action4", "#" %></li>
                <li class="divider"></li>
                <li><%= link_to "Action5", "#" %></li>
              </ul>
            </li>
            <li class="dropdown" id="preview-menu">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Utility<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Utility1", "#" %></li>
                <li><%= link_to "Utility2", "#" %></li>
                <li><%= link_to "Utility3", "#" %></li>
                <li><%= link_to "Utility4", "#" %></li>
                <li class="divider"></li>
                <li><%= link_to "Utility5", "#" %></li>
              </ul>
            </li>
            <li><%= link_to "Menu3", "#", id: "swatch-link"%></li>             
            <li><%= link_to "Menu4", "#", id: "swatch-link"%></li>             
          </ul>
          <ul class="nav pull-right" id="main-menu-right">
            <li><%= link_to "Help", "#"%></li>
            <li><%= link_to "About", "#"%></li>
            <li><%= link_to "Contact", "#"%></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", "#" %></li>
                <li><%= link_to "Settings", "#" %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", "#", method: "delete" %>
                </li>
                <li><%= link_to "Sign in", "#" %></li>
              </ul>
            </li>
          </ul>
         </div>
       </div>
     </div>
   </div>

  <!-- container -->
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>